import { routing } from './routing';

/**
 * Canonical URL construction for both locales.
 *
 * Two things live here because getting either wrong is invisible until search
 * engines act on it:
 *
 *  - The origin is written out in full, scheme included. The template kept it as
 *    a bare host, and interpolating that straight into a URL produced
 *    `priemersma.nl/about` — which is not a URL, and search engines reject those
 *    entries. The sitemap was emitting exactly that.
 *  - Every locale is prefixed (`localePrefix: 'always'`), so a URL names its
 *    language unambiguously: `/en/about` and `/nl/about`. Building that in one
 *    place keeps it that way.
 */

export const ORIGIN = 'https://priemersma.nl';

/**
 * Every static page, as a path below the locale root.
 *
 * The sitemap enumerates these. It used to read the template's `routes` config,
 * an object of route-to-boolean flags that also drove a client-side route guard;
 * the guard is gone, and a disabled route is now simply a route that does not
 * exist.
 */
export const SITE_PAGES = ['', '/about', '/work'] as const;

/**
 * The card shown when a link to this site is shared.
 *
 * One static image for the whole site, generated by `scripts/generate-og.mjs`.
 * It replaced a `/og` route that rendered a per-title card on demand — which
 * required a serverless function, and returned a 500 on every request because
 * the renderer cannot read the WOFF2 font it was given. A per-page title in a
 * link preview is not worth a runtime dependency that can fail; this cannot.
 */
export const OG_IMAGE = { url: `${ORIGIN}/og.png`, width: 1200, height: 630 };

/**
 * Absolute URL for a route in a given locale.
 *
 * @param path Route without a locale prefix, e.g. `/about`. Use `''` for home.
 */
export function localeUrl(locale: string, path = ''): string {
  return `${ORIGIN}/${locale}${path}`;
}

/**
 * Root-relative path for a route in a given locale.
 *
 * The counterpart to `localeUrl` for internal links, where an absolute URL is
 * unwanted. Same rule: the default locale carries no prefix.
 */
export function localePath(locale: string, path = ''): string {
  return `/${locale}${path}`;
}

/**
 * `alternates` metadata for a route: its canonical URL plus an hreflang entry
 * for every locale.
 *
 * Without this, Google has no way to know that `/about` and `/nl/about` are the
 * same page in two languages. It treats them as unrelated — or as duplicates —
 * and shows the wrong one to the wrong audience. `x-default` names the version
 * to serve when no language matches.
 */
export function localeAlternates(locale: string, path = '') {
  const languages = Object.fromEntries(
    routing.locales.map((l) => [l, localeUrl(l, path)])
  );

  return {
    canonical: localeUrl(locale, path),
    languages: {
      ...languages,
      'x-default': localeUrl(routing.defaultLocale, path),
    },
  };
}
